name = "literasity"
type = "webpack"
account_id = "88018ab33f1bd7fcbd871efd4776caa5" # inflight-menu.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "88018ab33f1bd7fcbd871efd4776caa5" # inflight-menu.workers.dev
zone_id = "b915b5c46a8b54c40fc30581f7314215"
route = "literasi.blog/*"

[site]
bucket = "_site"
entry-point = "workers-site"
